const ERROR_CODES = Object.freeze({
  FULFILLMENT_DISABLED: 'FULFILLMENT_DISABLED',
  ORDER_NOT_PAID: 'ORDER_NOT_PAID',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  SUPPLIER_NOT_SUPPORTED: 'SUPPLIER_NOT_SUPPORTED',
  SUPPLIER_PRODUCT_ID_MISSING: 'SUPPLIER_PRODUCT_ID_MISSING',
  FULFILLMENT_ALREADY_COMPLETED: 'FULFILLMENT_ALREADY_COMPLETED',
  FULFILLMENT_ALREADY_PROCESSING: 'FULFILLMENT_ALREADY_PROCESSING',
  SUPPLIER_ORDER_ALREADY_EXISTS: 'SUPPLIER_ORDER_ALREADY_EXISTS',
  SUPPLIER_STATUS_UNKNOWN: 'SUPPLIER_STATUS_UNKNOWN',
  DELIVERY_SCHEMA_UNKNOWN: 'DELIVERY_SCHEMA_UNKNOWN',
  SUPPLIER_API_ERROR: 'SUPPLIER_API_ERROR',
  SUPPLIER_AUTH_ERROR: 'SUPPLIER_AUTH_ERROR',
  MANUAL_REVIEW_REQUIRED: 'MANUAL_REVIEW_REQUIRED',
  UNSUPPORTED_FULFILLMENT_TYPE: 'UNSUPPORTED_FULFILLMENT_TYPE',
  PRODUCT_UNAVAILABLE: 'PRODUCT_UNAVAILABLE',
  PRODUCT_PRICE_INVALID: 'PRODUCT_PRICE_INVALID',
  FOXRELOAD_SANDBOX_NOT_CONFIGURED: 'FOXRELOAD_SANDBOX_NOT_CONFIGURED',
  FOXRELOAD_AUTH_FAILED: 'FOXRELOAD_AUTH_FAILED',
  FOXRELOAD_REQUEST_FAILED: 'FOXRELOAD_REQUEST_FAILED',
  FOXRELOAD_RATE_LIMITED: 'FOXRELOAD_RATE_LIMITED',
  FOXRELOAD_TIMEOUT: 'FOXRELOAD_TIMEOUT',
  FOXRELOAD_UNKNOWN_STATUS: 'FOXRELOAD_UNKNOWN_STATUS',
  FOXRELOAD_DELIVERY_UNKNOWN: 'FOXRELOAD_DELIVERY_UNKNOWN',
  FOXRELOAD_ORDER_CREATE_FAILED: 'FOXRELOAD_ORDER_CREATE_FAILED',
  FOXRELOAD_CUSTOMER_DATA_REQUIRED: 'FOXRELOAD_CUSTOMER_DATA_REQUIRED',
  FOXRELOAD_DUPLICATE_ORDER: 'FOXRELOAD_DUPLICATE_ORDER'
});

const fulfillmentError = (code, message = code) => {
  const error = new Error(message);
  error.code = code;
  return error;
};

module.exports = { ERROR_CODES, fulfillmentError };
