const FULFILLMENT_STATES = Object.freeze({
  NOT_REQUIRED: 'NOT_REQUIRED',
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  WAITING_SUPPLIER: 'WAITING_SUPPLIER',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  MANUAL_REVIEW: 'MANUAL_REVIEW'
});

module.exports = { FULFILLMENT_STATES };
